<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var array $data
 */

$escape = $this->plugin('escapeHtml');
?>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<?php if (!empty($data['heading'])): ?>
<h2><?= $escape($data['heading']) ?></h2>
<?php endif; ?>

<div id="tlandfilters">
<div id="timeline-<?= $block->id() ?>" class="timeline"></div>
<script>
    jQuery(document).ready(function($) {
        var params = <?= $data['viewer'] ?>;
        if (typeof params.centerDate === 'undefined') {
            params.centerDate = <?= json_encode($data['center_date']) ?>;
        }
        params.filters = <?= json_encode($data['filters']) ?>;
        params.userFilters = <?= json_encode($data['UserFilters']) ?>;
        params.UserCheckbox = <?= json_encode($data['UserCheckbox']) ?>;

        oTimeline.loadTimeline(
            'timeline-<?= $block->id() ?>',
            <?= json_encode($this->url('timeline-block', ['block-id' => $block->id()]), 320) ?>,
            params
        );
    });
</script>
<div class="filters" id="filters">
  <div class="fltLabelsButton" id="fltLabelsButton"></div>
  <div class="ckbfilters" id="ckbfilters"></div>
</div>
</div>

